### ISSUE TITLE
Why curl and not get_url?

### ISSUE THREAD

**Issue by onitake** [unstablereality/ansible-role-release-assets#3]
The get_url task from the Ansible core collection should be sufficient for downloading the final asset.

Is there a reason why you're invoking curl instead?

**Comment by lilithlavender** [comment]
It has to do with the `-L` flag that I'm passing to `curl`. There is a redirect involved in fetching the information and that was causing errors with `get_url`. I couldn't get it to respect that properly, so I had to invoke `curl` to get the download to work.

```
-L, --location
              (HTTP)  If  the  server  reports  that the requested page has moved to a different 
              location (indicated with a Location: header and a 3XX response code), this
              option will make curl redo the request on the new place.
```

**Comment by onitake** [comment]
I actuall found a way to do the redirect with Ansible... But it's messy.

This SO post explains why the redirect isn't straight-forward and won't work with get_url directly: https://stackoverflow.com/questions/20396329/how-to-download-github-release-from-private-repo-using-command-line/35688093#35688093

Essentially, it's S3 that chokes on the `Authorization` header, and it's not possible to have get_url only send it with the first request.

My solution works like this:

1. Query the asset id with `uri` (with `Accept: application/vnd.github.v3+json` and `Authorization: <token>`)
2. Query the asset URI with `uri` to see if we get redirected to S3 (with `Accept: application/octet-stream` and `Authorization: <token>`)
3. Save the returned content with `copy` if we didn't get a redirect
4. Download the file from S3 with `get_url` if we _did_ get redirected (without extra headers)
